name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Nodejs set up
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Client
        working-directory: client
        env:
          CI: false
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          set -x
          npm -v
          npm ci
          npm run build

      - name: Build Server
        working-directory: server
        env:
          CI: false
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          set -x
          npm -v
          npm ci
          npm run dev

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MERN_ECOMMERCE_B848D }}'
          channelId: live
          projectId: mern-ecommerce-b848d
          entryPoint: "./client"
